#+title: The spacemacs 30 day challenge


Currently available lessons

.. toctree::
   :maxdepth: 2

   day1
   day2

* How this course is structured

Learning Spacemacs takes some time, especially if you are new to Emacs, and/or Vim and/or most of the Emacs packages which are assembled in Spacemacs. Chances are that you won't have much fun if you start using Spacemacs for your day-to-day work right away. A better approach is to first learn how to use Spacemacs well, with dedicated lessons and examples.  Then you can use it for your work without too many "how-can-I-do-that-again" moments interrupting your newly acquired Spacemacs working flow. 

This course offers you a way to learn Spacemacs (including vim if you don't know it yet) in a few weeks, by spending 30 min every day on a topic from a well structured curriculum. You can become a Spacemacs power user in 30 days, with minimal per-day effort. Are you ready to take the challenge? Then read on!

Still there? Great, then let's turn you into a keyboard Jedi! And the sweetest thing: you don't have to choose one side of the force - here you will get the best of both vim and emacs, courtesy of the awesome Spacemacs team! 

The course has two main parts: a collection of *core modules*, teaching you the basics every spacemacs user should know. This includes, for example, basic knowledge of vim shortcuts or of the Emacs environment in which Spacemacs lives. Once you have got those basics down, you can cherry pick further modules from the *specialty section* depending on your personal requirements. For example, you could go for the module describing how to use your favorite programming language in Spacemacs, or you could decide to first go for one of the many possibilities that org-mode has to offer. Finally, for every specialty, you can decide how deep you want to dive into the topic: depending on the topic, up to three skill levels can be achieved: *Stormtropper*, *Padawan* and *Jedi*.

Take a look at the planned table of content of the course to get an idea of what is waiting for you in the coming days:

* Curriculum overview (planned)


** Core modules
Every major topic corresponds to one day..

- Read this before starting with day 1
  - Introduction and motivation
- Emacs/Spacemacs  (Strom trooper skills)
  - Basic interactions with the file system 
    - Opening, saving and closing files
    - dired basics
    - mkdir and friends
    - concept of the working directory in emacs
  - Starting external processes in emacs
  - Managing buffers, windows and frames 
  - Running commands from the minibuffer 
- Org mode (Storm trooper skills)
  - Org mode markup and using org mode as text processor
- Vim skill level (Stormtrooper skills)
  - Vim skill level: Stromtrooper 
- Vim skill level (Padawan skills)
- Emacs/Spacemacs skill level (Padawan skills)
  - Getting help in Emacs
  - Important concepts of the emacs editor
  - Basics of Spacemacs customization
    - Built-in capabilities you might want to activate now
      - Activating the paste ring
      - Contribution layers
    - Changing key bindings
  - Helm basics
  - Changing the look and feel of Emacs 

** Specialties
Every feature topic topic corresponds to one day, for now I haven't decided about skill levels in this part.

- (Spac)emacs killer features 
  - Dired and tramp
  - Using org mode to create project documentations
  - Org mode as literate programming environment 
  - Org mode as project management tool
  - Org mode as a personal wiki
  - Magit
  - Helm
  - ACEjump
  - Customization with Emacs Lisp
- (E)vi(l) killer features 
  - Tweaking vim to your needs
  - Mastering text objects
  - Mastering macros
  - Mastering repetitions 
  - Registers, appending to registers
- Programming and data analysis with emacs
  - Yasnippet
  - Org mode as a spreadsheet tool 
  - Handling images and figures in Emacs
- Adapting your system for optimal emacs/spacemacs usage
  - Reduce general mouse usage in linux
  - Streamline your system for your vim muscle memory
    - Use vim in your browser
    - Use vim in your pdf viewer
    - Use vim in your command line tools (actually, you always have, but perhaps didn't realize it)
